image: Visual Studio 2017

before_build:
  - nuget restore HW/HW_4/HW_4.1/Template/Template.sln

build:
  project: HW/HW_4/HW_4.1/Template/Template.sln

test_script:
  - dotnet test HW/HW_4/HW_4.1/Template/Template.sln