image: Visual Studio 2017

before_build:
  - nuget restore HW/HW_7/HW_7.1/Template/Template.sln

build:
  project: HW/HW_7/HW_7.1/Template/Template.sln

test_script:
  - dotnet test HW/HW_7/HW_7.1/Template/Template.sln