image: Visual Studio 2017

before_build:
  - nuget restore CW/CW_4.1/Task_1/Template/Template.sln

build:
  project: CW/CW_4.1/Task_1/Template/Template.sln

test_script:
  - dotnet test CW/CW_4.1/Task_1/Template/Template.sln