image: Visual Studio 2017

before_build:
  - nuget restore HW/HW_8/HW_8.2/GenericSet/GenericSet.sln

build:
  project: HW/HW_8/HW_8.2/GenericSet/GenericSet.sln

test_script:
  - dotnet test HW/HW_8/HW_8.2/GenericSet/GenericSet.sln