image: Visual Studio 2017

before_build:
  - nuget restore HW\HW_6\HW_6.2\EventLoopGame/EventLoopGame.sln

build:
  project: HW\HW_6\HW_6.2\EventLoopGame/EventLoopGame.sln

test_script:
  - dotnet HW\HW_6\HW_6.2\EventLoopGame/EventLoopGame.sln