image: Visual Studio 2017

before_build:
  - nuget restore HW/HW_2/HW_2.3/StackCalculatorHW/StackCalculatorHW.sln

build:
  project: HW/HW_2/HW_2.3/StackCalculatorHW/StackCalculatorHW.sln

test_script:
  - dotnet test HW/HW_2/HW_2.3/StackCalculatorHW/StackCalculatorHW.sln
