image: Visual Studio 2017

before_build:
  - nuget restore HW/HW_7/HW_7.2/Watch/Watch.sln

build:
  project: HW/HW_7/HW_7.2/Watch/Watch.sln

test_script:
  - dotnet test HW/HW_7/HW_7.2/Watch/Watch.sln